[clinic-ura-in]
exten => _X.,1,NoOp(Entrada URA Clinic Automation)
 same => n,Answer()
 same => n,Stasis(clinic-relationship)
 same => n,Hangup()

[clinic-ura-out]
exten => agendamento,1,Dial(PJSIP/fila-agendamento,30)
 same => n,Hangup()

exten => resultados,1,Dial(PJSIP/fila-resultados,30)
 same => n,Hangup()

exten => financeiro,1,Dial(PJSIP/fila-financeiro,30)
 same => n,Hangup()

exten => atendente,1,Dial(PJSIP/fila-atendimento,30)
 same => n,Hangup()
