[transport-udp]
type = transport
protocol = udp
bind = 0.0.0.0

[tronco-principal]
type = endpoint
context = clinic-ura-in
disallow = all
allow = ulaw,alaw
direct_media = no
outbound_auth = tronco-principal-auth
aors = tronco-principal-aor

[tronco-principal-auth]
type = auth
auth_type = userpass
username = usuario_do_tronco
password = senha_do_tronco

[tronco-principal-aor]
type = aor
contact = sip:provedor.exemplo:5060
